name: 'Node - install and build code'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
  node-version:
    description: 'The Node version that should be used for the build'
    required: true
    default: '16.x'
  build-command:
    description: 'The build command'
    required: true
    default: 'npm run build'
  
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Build code
      run: ${{ inputs.build-command }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
