name: 'Static website deployment'

inputs:
  aws-access-key-id:
    description: 'The AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'The AWS secret access key'
    required: true
  aws-region:
    description: 'The AWS region'
    required: true
  aws-s3-bucket-name:
    description: 'The S3 bucket name'
  node-version:
    description: 'The Node version that should be used for the build'
    required: true
    default: '16.x'
  build-command:
    description: 'The build command'
    required: true
    default: 'npm run build'
  dist-folder:
    description: 'The dist folder with the generated files to sync'
    required: true
    default: './dist'
  
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Build code
      run: ${{ inputs.build-command }}
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Sync files to S3 bucket
      run: aws s3 sync --delete ${{ inputs.dist-folder }} s3://${{ input.aws-s3-bucket-name }}
      shell: bash
