name: "PSQL over SSH"

inputs:
  working-directory:
    description: "The working directory"
    required: false
    default: "."
  ssh-private-key:
    description: "The SSH private key"
    required: true
  ssh-user:
    description: "The SSH user"
    required: true
  ssh-host:
    description: "The SSH host"
    required: true
  db-host:
    description: "The host where the action should be applied"
    required: true
  db-name:
    description: "The database name"
    required: false
    default: "bdp"
  db-user:
    description: "The database user"
    required: false
    default: "bdp"
  db-password:
    description: "The database password"
    required: true
  db-query:
    description: "The query that will be executed"
    required: true

runs:
  using: "composite"
  steps:
    # - name: Setup SSH connection
    #   env:
    #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    #   run: |
    #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
    #     ssh-add - <<< "${{ inputs.ssh-private-key }}"
    #   shell: bash
    - name: Setup SSH key
      run: echo "${{ inputs.ssh-private-key }}" > ssh-key
      shell: bash
    - name: Run the query
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      working-directory: ${{ inputs.working-directory }}
      run: ssh ${{ inputs.ssh-user }}@${{ inputs.ssh-host }} -i ssh-key -o StrictHostKeyChecking=no 'PGPASSWORD=${{ inputs.db-password }} psql -h ${{ inputs.db-host }} -U ${{ inputs.db-user }} -d ${{ inputs.db-name }} ${{ inputs.db-query }}'
      shell: bash
