name: 'Docker build and push image'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: 'infrastructure'
  docker-compose-file:
    description: 'The Docker Compose filename'
    required: true
    default: 'docker-compose.build.yml'
  docker-host:
    description: 'The Docker host'
    required: true
    default: 'docker.pkg.github.com'
  docker-username:
    description: 'The Docker username'
    required: true
  docker-password:
    description: 'The Docker password'
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-hosts }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: Build container images
      working-directory: ${{ inputs.working-directory }}
      run: docker-compose --no-ansi -f ${{ inputs.docker-compose-file }} build --pull
      shell: bash
    - name: Push container images
      working-directory: ${{ inputs.working-directory }}
      run: docker-compose --no-ansi -f ${{ inputs.docker-compose-file }} push
      shell: bash
