# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 'Java / Maven - install and test code'
description: 'Setup Java with Maven, and run a test command'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: '.'
  java-version:
    description: 'The Java version that should be used for the build'
    required: true
    default: '11'
  test-enabled:
    description: 'Enable test step'
    required: false
    default: 'true'
  test-command:
    description: 'The test command'
    required: true
    default: './mvnw test'
  
runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Test code
      if: ${{ inputs.test-enabled == 'true' }}
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.test-command }}
      shell: bash
