name: 'Builds webcomponents and pushes them to the store'

inputs:
  branch-name:
    description: 'The branch name for tag-version'
    required: true
    default: 'main'
  keycloak-secret:
    description: 'The keycloak client secret'
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.keycloak-secret }}
    - ${{ inputs.branch-name }}
