name: 'Push webcomponents to the store'

inputs:
  branch-name:
    description: 'The branch name for creating the version-tag visible in the store.'
    required: true
    default: 'main'
  keycloak-secret:
    description: 'The keycloak client secret.'
    required: true
  production:
    description: 'To push to the production store, set "true"'
    required: true
    default: 'false'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch-name }}
  env: 
    # TEST
    API_URL_TEST: https://api.webcomponents.opendatahub.testingmachine.eu/
    KEYCLOAK_URL_TEST: https://auth.opendatahub.testingmachine.eu/auth/
    KEYCLOAK_REALM_TEST: noi
    KEYCLOAK_CLIENT_ID_TEST: it.bz.opendatahub.webcomponents.cli

    # PROD
    API_URL_PROD: https://api.webcomponents.opendatahub.bz.it/
    KEYCLOAK_URL_PROD: https://auth.opendatahub.bz.it/auth/
    KEYCLOAK_REALM_PROD: noi
    KEYCLOAK_CLIENT_ID_PROD: it.bz.opendatahub.webcomponents.cli
    KEYCLOAK_CLIENT_SECRET: ${{ inputs.keycloak-secret }}

    PRODUCTION: ${{ inputs.production }}
