# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 'Webcomponent testing'

inputs:
  origin-test-enabled:
    description: 'Enable testing for a set origin parameter, currently tests whether or not the string origin is contained somewhere'
    required: false
    default: true
  origin-test-directory:
    description: 'The directory which will be searched for the occurrence of the origin test keyword'
    required: false
    default: 'src'
  origin-test-keyword:
    description: 'The keyword that the origin test searches for in the source code, only needed if the origin test is enabled'
    required: false
    default: 'origin'
  
runs:
  using: 'node16'
  main: 'index.js'