name: 'Docker deployment'

inputs:
  working-directory:
    description: 'The working directory'
    required: false
    default: 'infrastructure/ansible'
  playbook-file:
    description: 'The Ansible playbook filename'
    required: true
    default: 'deploy.yml'
  requirements-file:
    description: 'The Ansible requirements filename'
    required: true
    default: 'requirements.yml'
  hosts:
    description: 'The hosts where the deployment should be applied'
    required: true
  ssh-private-key:
    description: 'The SSH private key'
    required: true
  docker-host:
    description: 'The Docker host'
    required: true
    default: 'docker.pkg.github.com'
  docker-username:
    description: 'The Docker username'
    required: true
  docker-password:
    description: 'The Docker password'
    required: true
  project-name:
    description: 'The project name'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
